apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik-demo
  namespace: argocd   # Change the namespace to argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Diana-Dragoiu/argocd.git
    path: traefik
    helm:
      valueFiles:
      - /traefik/values.yaml   # Path to your values.yaml file
  destination:
    server: https://kubernetes.default.svc
    namespace: default
